### ISSUE TITLE
Refactor point filtering in dynamic vector tiling

### ISSUE THREAD

**Issue by jjnesbitt** [OpenGeoscience/uvdat#44]
Currently there's a hard threshold on the `z` value when returning point geometries, to prevent an overwhelming amount of points being rendered in certain datasets. This should be changed to one of the following approaches:

1. Server side density approach - Set a "max density" per z value and sub-sample the points to remain under that value. This has the benefit of keeping the implementation solely on the server side, as well as returning less data overall.
2. Client side - Selectively show points from the returned geometry on the rendered map. This may provide more fine tuned control, but imo is less ideal due to the fact that if we have multiple clients, the implementation may diverge.

**Comment by johnkit** [comment]
Should be moot once MapLibre is ready to go (#49).

**Comment by jjnesbitt** [comment]
Closed in favor of #49
